USE JIBE_Main_Training;
CREATE TABLE EMPLOYEEE (
emp_Id INT PRIMARY KEY,
emp_Name VARCHAR (50)
);
ALTER TABLE EMPLOYEEE ADD emp_Email VARCHAR(20);
SELECT * FROM EMPLOYEEE;

ALTER TABLE EMPLOYEEE DROP COLUMN emp_Email ;

TRUNCATE TABLE Employeee;

DROP TABLE Employeee;
